.github/workflows/doxygen-gh-pages.yml

Close #15 
- Doxygenで生成したhtmlをGithubPagesで公開する

feat: add doxygen actions

---

kyubic_ws/src/driver/depth_driver/CMakeLists.txt
kyubic_ws/src/driver/depth_driver/config/depth_driver.param.yaml
kyubic_ws/src/driver/depth_driver/include/depth_driver/depth_driver.hpp
kyubic_ws/src/driver/depth_driver/launch/depth_driver_launch.py
kyubic_ws/src/driver/depth_driver/src/depth_driver.cpp

Close #23 
- depthドライバのパラメータとlaunchファイルの追加

23 feat param

---

.gitignore
install.sh
kyubic_ws/src/driver/depth_driver/package.xml
kyubic_ws/src/driver/driver_node_manager/driver_node_manager/driver_node_manager.py
kyubic_ws/src/driver/driver_node_manager/package.xml
kyubic_ws/src/driver/driver_node_manager/setup.cfg
kyubic_ws/src/driver/driver_node_manager/setup.py
kyubic_ws/src/driver/driver_node_manager/test/test_copyright.py
kyubic_ws/src/driver/driver_node_manager/test/test_flake8.py
kyubic_ws/src/driver/driver_node_manager/test/test_pep257.py
nvim_setup.sh

ドライバーノードの管理GUI作成

---

kyubic_ws/src/driver/depth_driver/include/depth_driver/depth_driver.hpp
kyubic_ws/src/driver/depth_driver/src/depth_driver.cpp
kyubic_ws/src/driver/led_driver/CMakeLists.txt
kyubic_ws/src/driver/led_driver/config/led_driver.param.yaml
kyubic_ws/src/driver/led_driver/include/led_driver/led_driver.hpp
kyubic_ws/src/driver/led_driver/launch/led_driver_launch.py
kyubic_ws/src/driver/led_driver/package.xml
kyubic_ws/src/driver/led_driver/src/led_driver.cpp

Lightドライバの実装

---

kyubic_ws/src/driver/driver_msgs/CMakeLists.txt
kyubic_ws/src/driver/driver_msgs/msg/Thruster.msg
kyubic_ws/src/driver/imu_driver/src/imu_driver.cpp
kyubic_ws/src/driver/led_driver/src/led_driver.cpp
kyubic_ws/src/driver/thruster_driver/CMakeLists.txt
kyubic_ws/src/driver/thruster_driver/config/thruster_driver.param.yaml
kyubic_ws/src/driver/thruster_driver/include/thruster_driver/thruster_driver.hpp
kyubic_ws/src/driver/thruster_driver/launch/thruster_driver_launch.py
kyubic_ws/src/driver/thruster_driver/package.xml
kyubic_ws/src/driver/thruster_driver/src/thruster_driver.cpp

スラスタドライバの実装

---

Dockerfile

bash completionのセットアップをする

---

install.sh
ros2_start.sh
uninstall.sh

rdev rule のファイルがあれば，ハードリンクを作成するようにする  Status: Open.

---

kyubic_ws/src/driver/led_driver/src/led_driver.cpp

led制御マイコン側の形式が%だったので，8bit から 0-100 に変更

---

kyubic_ws/src/driver/thruster_driver/src/thruster_driver.cpp

char型の配列数の取得方法を修正

---

Dockerfile

sudoersがないという問題の解消

---

nvim_setup.sh

fix: update neovim download url

---

Dockerfile
entrypoint.sh
pyproject.toml
uv.lock

feat: add pyproject.toml

---

.github/pull_request_template.md

feat: close to resolve issue

---

kyubic_ws/src/control/manual/joy2wrench/CMakeLists.txt
kyubic_ws/src/control/manual/joy2wrench/config/joy2wrench.param.yaml
kyubic_ws/src/control/manual/joy2wrench/include/joy2wrench/joy2wrench.hpp
kyubic_ws/src/control/manual/joy2wrench/launch/joy2wrench_launch.py
kyubic_ws/src/control/manual/joy2wrench/package.xml
kyubic_ws/src/control/manual/joy2wrench/src/joy2wrench.cpp

feat: joy to wrench stamped message

---

install.sh
nvim_setup.sh

60 feat ros domain

---

docker/Dockerfile
docker/compose.yaml
docker/entrypoint.sh
docker/nvim_setup.sh
install.sh
ros2_start.sh
uninstall.sh

resolve #62 
- docker関連のファイルをルートディレクトリから，dockerディレクトリに移動

feat: create folder for docker file

---

docker/nvim_setup.sh

nvmの更新（node）

---

kyubic_ws/src/driver/imu_driver/src/g366.cpp

fix: coordinate system

---

kyubic_ws/src/tools/plotjugger/fix_axis_plotjugger/CMakeLists.txt
kyubic_ws/src/tools/plotjugger/fix_axis_plotjugger/config/fix_axis_plotjugger.param.yaml
kyubic_ws/src/tools/plotjugger/fix_axis_plotjugger/include/fix_axis_plotjugger/fix_axis_plotjugger.hpp
kyubic_ws/src/tools/plotjugger/fix_axis_plotjugger/launch/fix_axis_plotjugger_launch.py
kyubic_ws/src/tools/plotjugger/fix_axis_plotjugger/package.xml
kyubic_ws/src/tools/plotjugger/fix_axis_plotjugger/src/fix_axis_plotjugger.cpp
kyubic_ws/src/tools/plotjugger/plotjagger_msgs/CMakeLists.txt
kyubic_ws/src/tools/plotjugger/plotjagger_msgs/msg/MinMax.msg
kyubic_ws/src/tools/plotjugger/plotjagger_msgs/package.xml

plotjuggerの軸範囲固定用Publisherのパッケージを追加

---

docker/Dockerfile
docker/entrypoint.sh
docker/once_entrypoint.sh
install.sh

resolve #80
- コンテナ作成時に１度だけ実行するコマンドを entrypoint.sh から once_entrypoint.sh に切り出した
- once_entrypoint.sh はインストール時に実行

entrypointに不要なものを削除

---

docker/entrypoint.sh
docker/nvim_setup.sh
docker/once_entrypoint.sh
install.sh

コンテナのユーザーパスワードの入力省略，ros pkg のビルドをコンテナ作成時のみに変更

---

README.md

feat: add humble docs

---

.gitignore
README.md
docker/compose-nvidia.yaml
docker/compose.yaml
install.sh
ros2_start.sh
uninstall.sh

resolve #86
- NVIDIA GPUコンテナの対応
- 複数の環境を構築できるように，プロジェクト名での管理を採用

Nvidia GPU用コンテナの対応

---

README.md

Update README for humble

---

docker/Dockerfile
zellij_config.kdl

Zellijの導入、configファイルを作成

---

kyubic_ws/src/driver/driver_msgs/CMakeLists.txt
kyubic_ws/src/driver/driver_msgs/srv/Command.srv
kyubic_ws/src/driver/dvl_driver/include/dvl_driver/dvl_driver.hpp
kyubic_ws/src/driver/dvl_driver/include/dvl_driver/path_finder.hpp
kyubic_ws/src/driver/dvl_driver/src/dvl_driver.cpp
kyubic_ws/src/driver/dvl_driver/src/path_finder.cpp
kyubic_ws/src/tools/trdi_toolz/launch/trdi_toolz.launch.py
kyubic_ws/src/tools/trdi_toolz/package.xml
kyubic_ws/src/tools/trdi_toolz/setup.cfg
kyubic_ws/src/tools/trdi_toolz/setup.py
kyubic_ws/src/tools/trdi_toolz/test/test_copyright.py
kyubic_ws/src/tools/trdi_toolz/test/test_flake8.py
kyubic_ws/src/tools/trdi_toolz/test/test_pep257.py
kyubic_ws/src/tools/trdi_toolz/trdi_toolz/main.py

DVLの設定コマンド実装

---

kyubic_ws/src/driver/imu_driver/include/imu_driver/g366.hpp
kyubic_ws/src/driver/imu_driver/src/g366.cpp

IMUのエラー出力を増やす

---

docker/cmd_tools4client.sh
install.sh
uninstall.sh

クライアント側にサーバーアクセス関連のコマンドを登録

---

kyubic_ws/src/driver/driver_msgs/msg/Gnss.msg
kyubic_ws/src/driver/gnss_driver/gnss_driver/gnss_driver.py

resolve #119 
- geoid高さとgaoid分離を取得するメッセージ型をdriver_msgsに追加し、gnss_driverにPublish処理を追加
geoid_altitude が geoid高さ
geoid_separation が geoid分離

geoid高さとgaoid分離を取得するメッセージ型を追加、Publish

---

docker/Dockerfile
docker/once_entrypoint.sh
kyubic_ws/src/common/geodetic_converter/CMakeLists.txt
kyubic_ws/src/common/pid_controller/CMakeLists.txt
kyubic_ws/src/common/serial/CMakeLists.txt
kyubic_ws/src/common/timer/CMakeLists.txt
kyubic_ws/src/control/automatic/planning/path_planner/CMakeLists.txt
kyubic_ws/src/control/automatic/planning/planner_msgs/CMakeLists.txt
kyubic_ws/src/control/automatic/planning/projection_dynamic_look_ahead_planner/CMakeLists.txt
kyubic_ws/src/control/automatic/planning/wrench_planner/CMakeLists.txt
kyubic_ws/src/control/controller/p_pid_controller/CMakeLists.txt
kyubic_ws/src/control/manual/joy2wrench/CMakeLists.txt
kyubic_ws/src/driver/depth_driver/CMakeLists.txt
kyubic_ws/src/driver/driver_msgs/CMakeLists.txt
kyubic_ws/src/driver/driver_node_manager/setup.py
kyubic_ws/src/driver/dvl_driver/CMakeLists.txt
kyubic_ws/src/driver/gnss_driver/setup.py
kyubic_ws/src/driver/imu_driver/CMakeLists.txt
kyubic_ws/src/driver/led_driver/CMakeLists.txt
kyubic_ws/src/driver/thruster_driver/CMakeLists.txt
kyubic_ws/src/localization/localization/CMakeLists.txt
kyubic_ws/src/localization/localization_msgs/CMakeLists.txt
kyubic_ws/src/oak_create_mapping/setup.py
kyubic_ws/src/tools/path_generator/setup.py
kyubic_ws/src/tools/plotjuggler/fix_axis_plotjuggler/CMakeLists.txt
kyubic_ws/src/tools/real_time_plotter/setup.py
kyubic_ws/src/tools/real_time_plotter_msgs/CMakeLists.txt
kyubic_ws/src/tools/trajectory_viewer/setup.py
kyubic_ws/src/tools/trdi_toolz/setup.py
kyubic_ws/src/visualizer/web_controller/setup.py

resolve #143 
- CMAKE_EXPORT_COMPILE_COMANDSをコマンドラインからCMakeLists.txtに書く
- ROS2 Kaiju移行に対応するため，ament_auto_package()二オプション追加
- ビルドコマンドの変更とエイリアス追加

ビルド時の警告を消す
